
apiVersion: apps/v1
kind: Deployment
metadata:
  name: check-node-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: check-node-app
  template:
    metadata:
      labels:
        app: check-node-app
    spec:
      containers:
      - name: node-app
        image: localhost:5000/check-node-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: check-node-app-service
spec:
  type: NodePort
  selector:
    app: check-node-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
    nodePort: 30080
                